export default [
    "un soleil",
    "une lune",
    "une marguerite" ,
    "une enveloppe" ,
    "une étoile",
    "une main",
    "une cerise",
    "un nuage",
    "un chapeau",
    "un fromage" ,
    "une bouteille" ,
    "un escargot",
    "un anneau",
    "un ballon",
    "une banane",
    "une araignée" ,
    "une glace",
    "un chateau" ,
    "une casserole",
    "un papillon",
    "une voiture",
    "une maison",
    "un camion",
    "une pyramide",
    "un escargot",
    "un vase",
    "une chaise",
    "un avion",
    "un bateau",
    "un ours",
    "un sac",
    "une barbe",
    "une clé",
    "un visage",
    "une chaussette",
    "un lapin",
    "une fourchette",
    "un panier",
    "une feuille",
    "une montagne",
    "un oeil",
    "une moustache",
    "un café",
    "la pluie",
    "du pain",
    "un train",
    "un chat",
    "une plage",
    "un coquillage",
    "une horloge",
    "une chaussure",
    "un telephone",
    "un immeuble",
    "une vache",
    "un requin",
    "un ordinateur",
    "une moto",
    "un oeuf",
    "une reine",
    "un roi",
    "un vélo",
    "une poule",
    "un cheval",
    "un lion"
]